<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Database;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Change submit handler form_pets_owners.
 */
function pets_owners_storage_form_form_pets_owners_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'insert_db';
}

/**
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @throws \Exception
 */
function insert_db(&$form, FormStateInterface $form_state) {
  $connection = Database::getConnection();
  $connection->insert('pets_owners_storage')
    ->fields([
      'prefix' => $form_state->getValue('prefix'),
      'name' => $form_state->getValue('name'),
      'gender' => $form_state->getValue('gender'),
      'age' => $form_state->getValue('age'),
      'father' => $form_state->getValue('father'),
      'mother' => $form_state->getValue('mother'),
      'pets_name' => $form_state->getValue('pets_name'),
      'email' => $form_state->getValue('email'),
    ])
    ->execute();
  $form_state->setRedirect('pets_owners_storage.content');
}
